# Generated by Django 6.0.3 on 2026-04-05 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0002_remove_course_difficulty_coursecategory_theme_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="문제 제목")),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            (1, "Level 1"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                            (4, "Level 4"),
                            (5, "Level 5"),
                            (6, "Level 6"),
                            (7, "Level 7"),
                            (8, "Level 8"),
                            (9, "Level 9"),
                            (10, "Level 10"),
                        ],
                        default=1,
                        verbose_name="난이도",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(default=100, verbose_name="보상 포인트"),
                ),
                ("description", models.TextField(verbose_name="문제 설명")),
                ("flag", models.CharField(max_length=100, verbose_name="정답(Flag)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="출제자",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="course.coursecategory",
                        verbose_name="분야",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "시도 전"),
                            ("ATTEMPT", "시도 중"),
                            ("SOLVED", "해결"),
                        ],
                        default="TODO",
                        max_length=10,
                    ),
                ),
                ("solved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solve_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "problem")},
            },
        ),
    ]
