# Generated by Django 6.0.3 on 2026-04-07 20:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "problems",
            "0002_alter_solverecord_unique_together_problemattachment_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problemcomment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="solverecord",
            options={"ordering": ["-solved_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="solverecord",
            unique_together={("user", "problem")},
        ),
    ]
