# Generated by Django 6.0.3 on 2026-04-06 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("COURSE", "강의 수강"),
                    ("PROBLEM", "문제 풀이"),
                    ("SYSTEM", "시스템 알림"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="event_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="행사 진행 일자 (Event용)"
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="message",
            field=models.TextField(verbose_name="활동 내역"),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="posted_as",
            field=models.CharField(
                choices=[("News", "News"), ("Event", "Event")],
                max_length=10,
                verbose_name="게시글 분류",
            ),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="summary",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="내용 요약"
            ),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="title",
            field=models.CharField(max_length=200, null=True, verbose_name="제목"),
        ),
    ]
