# Generated by Django 6.0.3 on 2026-04-07 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_activitylog_options_activitylog_action_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="일정명")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="상세 내용"),
                ),
                ("start_date", models.DateTimeField(verbose_name="시작 일시")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="종료 일시"
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, verbose_name="동아리 전체 일정 여부"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
    ]
