# Generated by Django 6.0.3 on 2026-04-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="user",
        ),
        migrations.DeleteModel(
            name="NewsAndEvents",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="session",
        ),
        migrations.DeleteModel(
            name="ActivityLog",
        ),
        migrations.DeleteModel(
            name="Semester",
        ),
        migrations.DeleteModel(
            name="Session",
        ),
    ]
