# Generated by Django 6.0.3 on 2026-04-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_usercourseprogress_options_and_more"),
        ("core", "0004_remove_activitylog_user_delete_newsandevents_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("COURSE", "강의 수강"),
                            ("PROBLEM", "문제 풀이"),
                            ("SYSTEM", "시스템 알림"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(verbose_name="활동 내역")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="course.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "action_type", "course"),
                        name="unique_user_course_activity",
                    )
                ],
            },
        ),
    ]
