# Generated by GitHub Copilot on 2026-04-08

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_activitylog"),
        ("problems", "0003_alter_problemcomment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="problems.problem",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="activitylog",
            name="unique_user_course_activity",
        ),
        migrations.AddConstraint(
            model_name="activitylog",
            constraint=models.UniqueConstraint(
                condition=Q(("action_type", "COURSE"), ("course__isnull", False)),
                fields=("user", "action_type", "course"),
                name="unique_user_course_completion_activity",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitylog",
            constraint=models.UniqueConstraint(
                condition=Q(("action_type", "PROBLEM"), ("problem__isnull", False)),
                fields=("user", "action_type", "problem"),
                name="unique_user_problem_solve_activity",
            ),
        ),
    ]
