# Generated by Django 6.0.3 on 2026-04-04 17:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="트랙 이름 (예: Web Hacking)",
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="트랙 설명"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("title", models.CharField(max_length=200, verbose_name="강의명")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="강의 코드 (예: WEB01)"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="강의 요약"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        default="Beginner",
                        max_length=20,
                        verbose_name="난이도",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="course_thumbnails/",
                        verbose_name="강의 썸네일",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당 강사/운영진",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.coursecategory",
                        verbose_name="소속 트랙",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="자료명")),
                (
                    "file",
                    models.FileField(
                        help_text="허용 확장자: pdf, docx, xls, ppt, zip, rar, 7zip 등",
                        upload_to="course_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "pdf",
                                    "docx",
                                    "doc",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                    "zip",
                                    "rar",
                                    "7zip",
                                ]
                            )
                        ],
                    ),
                ),
                ("upload_time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="영상 제목")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "video",
                    models.FileField(
                        upload_to="course_videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "mkv", "wmv", "3gp", "f4v", "avi", "mp3"]
                            )
                        ],
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="영상 요약"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="수강 완료 여부"),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(default=0, verbose_name="진도율(%)"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수강일"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to="course.course",
                        verbose_name="강의",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="동아리원",
                    ),
                ),
            ],
            options={
                "verbose_name": "동아리원 수강 진도",
                "verbose_name_plural": "동아리원 수강 진도 목록",
                "unique_together": {("user", "course")},
            },
        ),
    ]
