# Generated by Django 6.0.3 on 2026-04-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="difficulty",
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="theme_color",
            field=models.CharField(
                default="bg-blue-500",
                help_text="Tailwind 색상 클래스 입력 (예: bg-blue-500)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="강의 코드"
            ),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="title",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="트랙 이름"
            ),
        ),
    ]
