# Generated by Django 6.0.3 on 2026-04-06 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_remove_course_difficulty_coursecategory_theme_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="단원명 (예: SECCOMP)"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="정렬 순서")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="course.course",
                        verbose_name="소속 강의",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="수업명 (예: Background: SECCOMP)"
                    ),
                ),
                ("content", models.TextField(verbose_name="강의 내용 (HTML/Markdown)")),
                ("order", models.IntegerField(default=0, verbose_name="정렬 순서")),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="course.unit",
                        verbose_name="소속 단원",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
