# Generated by Django 6.0.3 on 2026-04-06 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_unit_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="unit",
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="course.course",
                verbose_name="소속 강의",
            ),
            preserve_default=False,
        ),
    ]
