# Generated by Django 6.0.3 on 2026-04-06 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_remove_lesson_unit_lesson_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usercourseprogress",
            options={
                "verbose_name": "수강 진도",
                "verbose_name_plural": "수강 진도 목록",
            },
        ),
        migrations.AlterUniqueTogether(
            name="usercourseprogress",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="usercourseprogress",
            name="completed_lessons",
            field=models.ManyToManyField(
                blank=True, to="course.lesson", verbose_name="완료된 수업"
            ),
        ),
        migrations.AlterField(
            model_name="usercourseprogress",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course.course",
                verbose_name="강의",
            ),
        ),
        migrations.AlterField(
            model_name="usercourseprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="수강생",
            ),
        ),
        migrations.RemoveField(
            model_name="usercourseprogress",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="usercourseprogress",
            name="progress_percentage",
        ),
        migrations.RemoveField(
            model_name="usercourseprogress",
            name="updated_at",
        ),
    ]
