# Generated by Django 6.0.3 on 2026-04-06 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_usercourseprogress_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usercourseprogress",
            options={},
        ),
        migrations.AlterField(
            model_name="usercourseprogress",
            name="completed_lessons",
            field=models.ManyToManyField(blank=True, to="course.lesson"),
        ),
        migrations.AlterField(
            model_name="usercourseprogress",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.course"
            ),
        ),
        migrations.AlterField(
            model_name="usercourseprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercourseprogress",
            unique_together={("user", "course")},
        ),
    ]
