# Generated by Django 6.0.3 on 2026-04-08 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coursecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='수강 기한'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(help_text='허용 확장자: pdf, docx, xls, ppt, zip, rar, 7zip, jpg, png, webp, txt 등', upload_to='course_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', '7zip', 'txt', 'csv', 'md', 'jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
