# Generated by Django 6.0.3 on 2026-04-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="문제명")),
                ("slug", models.SlugField(unique=True, verbose_name="문제 코드")),
                ("statement", models.TextField(verbose_name="문제 본문")),
                (
                    "input_description",
                    models.TextField(blank=True, verbose_name="입력 설명"),
                ),
                (
                    "output_description",
                    models.TextField(blank=True, verbose_name="출력 설명"),
                ),
                (
                    "sample_input",
                    models.TextField(blank=True, verbose_name="예제 입력"),
                ),
                (
                    "sample_output",
                    models.TextField(blank=True, verbose_name="예제 출력"),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=2, verbose_name="시간 제한(초)"
                    ),
                ),
                (
                    "memory_limit",
                    models.PositiveIntegerField(
                        default=256, verbose_name="메모리 제한(MB)"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="공개 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "문제",
                "verbose_name_plural": "문제 목록",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ContestProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=10, verbose_name="문제 번호")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "score",
                    models.PositiveIntegerField(default=100, verbose_name="배점"),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_problems",
                        to="contest.contest",
                        verbose_name="대회",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_links",
                        to="contest.problem",
                        verbose_name="문제",
                    ),
                ),
            ],
            options={
                "verbose_name": "대회 문제",
                "verbose_name_plural": "대회 문제 목록",
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contest", "problem"), name="unique_contest_problem"
                    ),
                    models.UniqueConstraint(
                        fields=("contest", "label"), name="unique_contest_label"
                    ),
                ],
            },
        ),
    ]
