# Generated by Django 6.0.3 on 2026-04-06 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0002_problem_contestproblem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="참가 시각"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="참가 활성 상태"),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="contest.contest",
                        verbose_name="대회",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "대회 참가자",
                "verbose_name_plural": "대회 참가자 목록",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contest", "user"), name="unique_contest_participant"
                    )
                ],
            },
        ),
    ]
