# Generated by Django 6.0.3 on 2026-04-06 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0003_contestparticipant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("cpp", "C++"),
                            ("java", "Java"),
                        ],
                        default="python",
                        max_length=20,
                        verbose_name="제출 언어",
                    ),
                ),
                ("source_code", models.TextField(verbose_name="소스 코드")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PENDING", "채점 대기"),
                            ("AC", "정답"),
                            ("WA", "오답"),
                            ("TLE", "시간 초과"),
                            ("MLE", "메모리 초과"),
                            ("RE", "런타임 에러"),
                            ("CE", "컴파일 에러"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="채점 결과",
                    ),
                ),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="실행 시간(ms)"
                    ),
                ),
                (
                    "memory_kb",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="메모리 사용량(KB)"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제출 시각"),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="contest.contest",
                        verbose_name="대회",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="contest.problem",
                        verbose_name="문제",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "대회 제출",
                "verbose_name_plural": "대회 제출 목록",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
