# Generated by Django 6.0.3 on 2026-04-06 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0004_contestsubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField(verbose_name="입력 데이터")),
                ("expected_output", models.TextField(verbose_name="기대 출력")),
                (
                    "is_sample",
                    models.BooleanField(default=False, verbose_name="예제 여부"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="contest.problem",
                        verbose_name="문제",
                    ),
                ),
            ],
            options={
                "verbose_name": "테스트케이스",
                "verbose_name_plural": "테스트케이스 목록",
                "ordering": ["order", "id"],
            },
        ),
    ]
