# Generated by Django 6.0.3 on 2026-04-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0005_testcase"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestsubmission",
            name="judge_message",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="채점 메시지"
            ),
        ),
        migrations.AddField(
            model_name="contestsubmission",
            name="passed_count",
            field=models.PositiveIntegerField(default=0, verbose_name="통과 테스트 수"),
        ),
        migrations.AddField(
            model_name="contestsubmission",
            name="total_count",
            field=models.PositiveIntegerField(default=0, verbose_name="전체 테스트 수"),
        ),
    ]
