# Generated by Django 6.0.3 on 2026-04-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0006_contestsubmission_judge_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionTestCaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(default=False, verbose_name="통과 여부"),
                ),
                (
                    "actual_output",
                    models.TextField(blank=True, verbose_name="실제 출력"),
                ),
                (
                    "judge_message",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="채점 메시지"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcase_results",
                        to="contest.contestsubmission",
                        verbose_name="제출",
                    ),
                ),
                (
                    "testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_results",
                        to="contest.testcase",
                        verbose_name="테스트케이스",
                    ),
                ),
            ],
            options={
                "verbose_name": "제출 테스트케이스 결과",
                "verbose_name_plural": "제출 테스트케이스 결과 목록",
                "ordering": ["testcase__order", "id"],
            },
        ),
    ]
