# Generated by Django 6.0.3 on 2026-04-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0007_submissiontestcaseresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "대기 중"),
                            ("RUNNING", "채점 중"),
                            ("DONE", "완료"),
                            ("FAILED", "실패"),
                        ],
                        default="QUEUED",
                        max_length=20,
                        verbose_name="작업 상태",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="오류 메시지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="시작 시각"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시각"
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_task",
                        to="contest.contestsubmission",
                        verbose_name="제출",
                    ),
                ),
            ],
            options={
                "verbose_name": "채점 작업",
                "verbose_name_plural": "채점 작업 목록",
            },
        ),
    ]
