# Generated by Django 6.0.3 on 2026-04-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsAndEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, null=True, verbose_name="제목"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, max_length=200, null=True, verbose_name="내용 요약"
                    ),
                ),
                (
                    "posted_as",
                    models.CharField(
                        choices=[("News", "News"), ("Event", "Event")],
                        max_length=10,
                        verbose_name="게시글 분류",
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("upload_time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "event_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="행사 진행 일자 (Event용)"
                    ),
                ),
            ],
        ),
    ]
