# Generated by Django 6.0.3 on 2026-04-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsandevents",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="activities/thumbnails/",
                verbose_name="썸네일",
            ),
        ),
    ]
