# Generated by Django 6.0.3 on 2026-04-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_points",
            field=models.IntegerField(default=0, verbose_name="누적 포인트"),
        ),
    ]
