# Generated by Django 6.0.3 on 2026-04-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_total_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="bio",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="한 줄 소개"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="blog_url",
            field=models.URLField(blank=True, verbose_name="블로그 주소"),
        ),
        migrations.AddField(
            model_name="student",
            name="github_url",
            field=models.URLField(blank=True, verbose_name="GitHub 주소"),
        ),
        migrations.AddField(
            model_name="student",
            name="level",
            field=models.IntegerField(default=1, verbose_name="현재 레벨"),
        ),
    ]
