# Generated by Django 6.0.3 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_student_bio_student_blog_url_student_github_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="닉네임"),
        ),
    ]
