# Generated by Django 5.2.14 on 2026-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_student_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_number",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="학번"
            ),
        ),
    ]
